### ISSUE TITLE
 大佬，方便加个站内搜索吗？

### ISSUE THREAD

**Issue by luolovehk** [lovewhoilove/lovewhoilove.github.io#1]
手机端的时候，有三个搜索功能了。右上角一个，右下角一个，页面一个。

**Comment by lovewhoilove** [comment]
惭愧，这个主题还是我改的别人的，我也不清楚怎么加，我搜到一篇文章，https://jimmysong.io/hugo-handbook/steps/searching-plugin.html，之后有空了再加吧😁

**Comment by luolovehk** [comment]
> 惭愧，这个主题还是我改的别人的，我也不清楚怎么加，我搜到一篇文章，https://jimmysong.io/hugo-handbook/steps/searching-plugin.html ，之后有空了再加吧😁

这个主题UI很好看😄😄，我看代码里面好像还有个夜间模式的，功能还没有实现。

**Comment by lovewhoilove** [comment]
说实话，他那个夜间模式有点问题，我干脆就把它隐藏了，我并不专业，只是改改自己能用就行，就是纯粹PC端导航首页，你说的那个之后看看吧，目前暂时先这样（😅）

**Comment by lovewhoilove** [comment]
> 

你要是想自己改，建议下载这个项目：https://github.com/iplaycode/webstack-hugo ，我看日志有夜间模式

**Comment by luolovehk** [comment]
> > 
> 
> 你想自己修改，建议下载这个项目：https://github.com/iplaycode/webstack-hugo，我看日志有夜间模式

没技术。不折腾，我用着这个就好了

**Comment by luolovehk** [comment]
> > > > 
> > > 
> > > 
> > > 你想自己修改，建议下载这个项目：[https://github.com/iplaycode/webstack-hugo，我看日志有夜间模式](https://github.com/iplaycode/webstack-hugo%EF%BC%8C%E6%88%91%E7%9C%8B%E6%97%A5%E5%BF%97%E6%9C%89%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F)
> > 
> > 
> > 没技术。不折腾，我用着这个就好了
> 
> 最近我github无法push，我就放到gitee上了，那个最近一直在更新，这个后面若是能正常推送，我还会继续用，gitee地址：https://lovewhoilove.gitee.io/

感谢大佬的分享，我尝试了一下用HUGO，发现修改生成也挺方便的
